title: Jonathan's Coding Journal
first_name: Jonathan
last_name: Pugh
email: jdspugh@gmail.com
description: Coding Journal
twitter_username: jdspugh
github_username:  jdspugh
theme: minima
disqus:
  shortname: tech-blog-jdspugh