title: Jonathan's Tech Blog
first_name: Jonathan
last_name: Pugh
email: jdspugh@gmail.com
description: >
  Tech Blog
baseurl: "/"
url: "https://jdspugh.github.io"
twitter_username: jdspugh
github_username:  jdspugh
theme: minima
kramdown:
  auto_ids: true
