title: Jonathan's Tech Blog
first_name: Jonathan
last_name: Pugh
email: jdspugh@gmail.com
description: Tech Blog
twitter_username: jdspugh
github_username:  jdspugh
theme: minima
disqus:
  shortname: tech-blog-jdspugh
