title: Jonathan's Coding Journal
first_name: Jonathan
last_name: Pugh
email: jdspugh@gmail.com
description: Jonathan Pugh B.Sc.(Hons) M.Sc.
theme: minima
google_analytics: G-M7VGBQVJM8
twitter_username: jdspugh
github_username:  jdspugh
disqus:
  shortname: tech-blog-jdspugh